name: stripe_dart
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: SpivEgin <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 path: ^1.4.1
 js: ^0.6.1+1

dev_dependencies:
  test: ^1.0.0
